# @package _global_

model_name: "scattering"

model:
  _target_: pcnn.models.pcnn.PCNN
  num_layers: 1
  hidden_dim: 4
  lr: 0.001
  compute_P: False
  layer:
    filter_method: extract_scattering
    combine_method: identity
    activation: identity
    cross_channel_conv: identity
    reshaping: identity
    num_filters: ${model.hidden_dim}
    num_combine: 1
    num_cross_channels: 1
  graph_construct:
    k: null
    graph_type: null
    compute_laplacian: epsilon
    compute_scattering_feats: True
    eps: 3
    K: 20
    d: 2
    eps_quantile: 0.5
    norm_list: [1,2,3,4]
    J: 8

